### ISSUE TITLE
XXH3-128 support?

### ISSUE THREAD

**Issue by thomcc** [shepmaster/twox-hash#104]
I was hoping to use this library for XXH3 in a case that requires 128-bit checksums, but it doesn't seem like it's supported (unless I've lost by brain and missed it). I obviously don't need a Hasher implementation.

**Comment by shepmaster** [comment]
It’s over in https://github.com/shepmaster/twox-hash/tree/xxh3-128. Care to test that branch and see if it works for you?

Unfortunately it doesn’t match the currently *released* version of the C reference implementation because they had a bug which has since been fixed but not yet released.

**Comment by thomcc** [comment]
That branch does work for me it seems, although my testing was far from exhaustive.

**Comment by shepmaster** [comment]
Released as 2.1.0
