### ISSUE TITLE
“buffer was not aligned for 64-bit numbers” at src\sixty_four.rs:188:17 on 32-bit Windows

### ISSUE THREAD

**Issue by blackbeam** [shepmaster/twox-hash#29]
Hi.

My windows CI is panicking in twox_hash 1.4.0 on i686 ([build log](https://ci.appveyor.com/project/blackbeam/mysql-async/builds/25588910/job/d5say70fms60jav9?fullLog=true#L285)).
All builds: [link](https://ci.appveyor.com/project/blackbeam/mysql-async/builds/25588910)

Builds are fine for 1.2.0 ([link](https://ci.appveyor.com/project/blackbeam/mysql-async/builds/25607653)) and 1.3.0 ([link](https://ci.appveyor.com/project/blackbeam/mysql-async/builds/25610279))

**Comment by shepmaster** [comment]
Yes, it’s intended that 32-bit is supported. I have an idea on a fix, but you may wish to pin your build to 1.3.0 until I have an opportunity to try it out.

**Comment by shepmaster** [comment]
The code in question:

https://github.com/shepmaster/twox-hash/blob/v1.4.0/src/sixty_four.rs#L188-L191

**Comment by shepmaster** [comment]
Could you easily test against https://github.com/shepmaster/twox-hash/tree/32-bit? I’m having a very hard time reproducing the bug locally as I don’t have access to 32-bit Windows and 32-bit Linux doesn’t seem to cause the problem.

**Comment by shepmaster** [comment]
I believe that the proposed branch will fix the problem. I was able to setup a 32-bit Windows VM with MySQL, run your testsuite and reproduce the problem. Swapping in the branch caused the tests to pass.

I’ll release this shortly, assuming our CI passes.

**Comment by shepmaster** [comment]
Released in 1.4.1. Please let me know if you find any other issues and sorry for the inconvenience!
