### ISSUE TITLE
Mind alignment

### ISSUE THREAD

**Issue by bluss** [shepmaster/twox-hash#3]
The code in number_streams is cool, but from a cursory look it seems to cast a u8 pointer directly to a u64 pointer, which is not correct in general.

This depends on the platform / architecture, some tolerate loading from ill aligned addresses fine and some don't. x86-64 is generally fine, and why we don't see much trouble, but on other platforms you will.

This [blog](http://blog.reverberate.org/2012/01/state-of-hash-functions-2012.html) mentions using `memcpy` to let the compiler decide how to load from a possibly ill aligned address. This is what google's farmhash does too, and it's also what I updated SipHash to do, see rust-lang/rust#27280.

**Comment by bluss** [comment]
It's a tricky topic. [xxhash's recent blog on *Accessing unaligned memory*](http://fastcompression.blogspot.se/2015/08/accessing-unaligned-memory.html)

**Comment by shepmaster** [comment]
I think this is *finally* addressed!

68fede8a9ad8c094664525622270da6966821b1f
