### ISSUE TITLE
[Noob Question] Can I use it as In Memory Database ?

### ISSUE THREAD

**Issue by bcashier** [shepmaster/twox-hash#35]
Hi,

I receive data regulary from online users, and before storing them inside MySQL database, I have to compare them and match some of them in order, duplicate, update, etc ... before they go to MySQL database.

Can I use twox-hash for this purpose please ? Like putting the data received from users in queue so they the new incoming can be compared to them ? If yes, how much of datas can be stored on the Hash ?

Is there a way I can call the queue depend on the first inserted ?

Thank you in advance.

**Comment by shepmaster** [comment]
> Can I use twox-hash for this purpose

twox-hash is *just* a hashing algorithm. If you have access to a queue data structure that uses a hashing algorithm to track uniqueness and it allows you to specify that hashing algorithm, then this should work well for that case.

I am unaware of any direct datastructure like that. 

The closest I know of would be to combine a [`BinaryHeap`](https://doc.rust-lang.org/std/collections/index.html#use-a-binaryheap-when) with a [`*Set`](https://doc.rust-lang.org/std/collections/index.html#use-the-set-variant-of-any-of-these-maps-when). 

There's also [indexmap](https://github.com/bluss/indexmap), which preserves insertion *order*, but it sounds like you might need to order by other criteria.

> how much of datas can be stored on the Hash

That's entirely dependent on your data, your system, and what kind of guarantees you need to provide.

**Comment by bcashier** [comment]
@shepmaster Thank you sir for your answer :)

Interesting referance out there, is it possible to combine [indexmap](https://github.com/bluss/indexmap) with Twox-Hash ? So that I can get ordered queued datas and fastest iteration and manipulation ?

Thanks again and sorry for your time :)

**Comment by shepmaster** [comment]
> is it possible to combine [indexmap](https://github.com/bluss/indexmap) with Twox-Hash

Yes, [`with_capacity_and_hasher`](https://docs.rs/indexmap/1.0.2/indexmap/map/struct.IndexMap.html#method.with_capacity_and_hasher) allows you to specify the hashing algorithm.

**Comment by bcashier** [comment]
@shepmaster You are awesome !

Thank you sir for your help and your time :) Appreciated.
