### ISSUE TITLE
Only works on unstable rust

### ISSUE THREAD

**Issue by rw** [shepmaster/twox-hash#4]
How hard would it be to make `twox-hash` work with stable rust? I get the following error when installing the crate:

```
error: #[feature] may not be used on the stable release channel
#![feature(hashmap_hasher)]
```

**Comment by shepmaster** [comment]
It depends on what you want the crate to do in stable :smile_cat:. Currently, the ability to use custom `Hasher` implementations [is feature gated](https://github.com/rust-lang/rust/issues/27713). There's nothing this crate can do about that until Rust marks it stable.

If you'd like the ability to simply run the hash logic and get out a `u64` of the hashed value, then I can certainly add a feature flag to split those two concepts apart.

What is your end goal?

**Comment by shepmaster** [comment]
Rust 1.7 stabilized hashing, and [version 1.0](https://github.com/shepmaster/twox-hash/releases/tag/v1.0.0) of this crate has been released supporting it.
