### ISSUE TITLE
How to use hasher directly?

### ISSUE THREAD

**Issue by gembin** [shepmaster/twox-hash#42]
How to use hasher directly? Both methods `write` and `finish` are private.
```rust
let mut hasher = XxHash64::default();
hasher.write(b"Hello");
let hash = hasher.finish();
```

**Comment by shepmaster** [comment]
Does something prevent you from using the hashing traits from the standard library?

```rust
fn main() {
    use std::hash::Hasher;
    let mut hasher = twox_hash::XxHash64::default();
    hasher.write(b"Hello");
    let hash = hasher.finish();
}
```

**Comment by gembin** [comment]
Yes, it works, thanks!   However the IDE(CLion) shows 
the method is `private`, it should be an IDE issue.

**screenshot**
<img width="495" alt="screenshot" src="https://user-images.githubusercontent.com/26495/74618246-c0c39f00-50e5-11ea-8bf6-8683ccb86960.png">

**Comment by shepmaster** [comment]
> the IDE(CLion) shows
> the method is `private`, it should be an IDE issue.

It's tricky, as there are actually *two* methods: there's an internal method called `finish`, and there's the public trait method of the same name.

**Comment by kueue-io** [comment]
Yes, it's tricky. Perhaps rename the internal method would avoid such issue.
