### ISSUE TITLE
Non-copying hashing

### ISSUE THREAD

**Issue by arxanas** [shepmaster/twox-hash#43]
I'm trying to use xxhash to replace the hashing at https://github.com/facebook/hhvm/blob/6bcb839d04b5f93b0b5624266d7918b9144f57d4/hphp/hack/src/deps/typing_deps.ml#L74-L87. This is the hashing for the dependency graph in Hack. Currently, it's implemented in OCaml, and I'm trying to port it to Rust. It's a very hot code path.

The existing hashing in OCaml is based on a variant of Murmur3. The input to the hash in this case is a single `u8`, and then either one or two strings. Microbenchmarks and perf tests indicate that `twox-hash` introduces a regression in overall performance.

I also tried using the `fasthash` crate, which offers bindings to xxhash implemented in C. The results are that:

* Using `xxhash` through the `Hasher` trait, which copies strings into a temporary buffer before hashing the entire thing, introduces a similar performance regression.
* Using `xxhash` but avoiding buffer copies (by using the non-`Hasher` implementation which takes a single string and returns a `u32`, then using that as the seed for the next hash) performs faster than the existing OCaml hashing.

I notice that this implementation of hashing also seems to involve copying the input buffer: https://github.com/shepmaster/twox-hash/blob/master/src/thirty_two.rs#L37. Is it possible to get a version of the hashing which does not involve copying? What is the rationale for using a buffer to begin with — is this an important performance consideration I should be taking into account when relying on high-performance hashing?

**Comment by shepmaster** [comment]
I don't know how much you know about xxhash, so bear with me if I repeat something. 

The general idea of xxhash is that it pretends that memory is just a giant blob of 32 (or 64)-bit values. It then works on 4x 32(64)-bit values. This works well for x86 systems where alignment rules are relatively relaxed and when the data is noticeably longer than 32(64) bits.

For some benchmarks of common Rust hashes, check out https://github.com/Gankra/hash-rs

We [have our own benchmarks](https://github.com/shepmaster/twox-hash/blob/5c9a4690f576a20280a9ecbc4cbdc3ab2fff26e2/comparison/benches/bench.rs), comparing us to [the C implementation](https://github.com/shepmaster/twox-hash/blob/5c9a4690f576a20280a9ecbc4cbdc3ab2fff26e2/comparison/src/c_xxhash.rs)

It does look like our delta from C has increased a bit, and I might need to look into that:

```
XxHash32/1024 bytes/offset 0
    time:   [194.75 ns 201.79 ns 209.05 ns]
    thrpt:  [4.8985 Gelem/s 5.0746 Gelem/s 5.2580 Gelem/s]
XxHash32/1024 bytes/offset 1
    time:   [200.74 ns 205.56 ns 210.85 ns]
    thrpt:  [4.8613 Gelem/s 4.9865 Gelem/s 5.1062 Gelem/s]

XxHash32 (C)/1024 bytes/offset 0                        
    time:   [129.31 ns 132.99 ns 137.30 ns]
    thrpt:  [7.4583 Gelem/s 7.6997 Gelem/s 7.9187 Gelem/s]
XxHash32 (C)/1024 bytes/offset 1
    time:   [130.69 ns 132.33 ns 134.12 ns]
    thrpt:  [7.6423 Gelem/s 7.7460 Gelem/s 7.8429 Gelem/s]
```

> I notice that this implementation of hashing also seems to involve copying the input buffer

The code tries very hard to not perform any copies. The code you link to is for buffering pieces of data until we have 4x values. If you provide more data than that, we will read directly from the input with minimal copying (beyond that needed for the hash computations itself). The optimal case is if you provide an exact multiple of 4x 32(64) bits.

> I also tried using the `fasthash` crate

Did you compare the end results of the two methods? I would have expected that they produce differing hashes.

> then using that as the seed for the next hash

This is a clever idea, and one that should be amenable to usage with this crate, assuming that the results aren't different from the reference implementation *or* you are ok with the different results. Depending on the exact interface you need, you can create a new hasher [from a seed](https://docs.rs/twox-hash/1.5.0/twox_hash/struct.XxHash32.html#method.with_seed) and then hash the string in one shot, then roll the output forward.

**Comment by arxanas** [comment]
> The general idea of xxhash is that it pretends that memory is just a giant blob of 32 (or 64)-bit values. It then works on 4x 32(64)-bit values. This works well for x86 systems where alignment rules are relatively relaxed and when the data is noticeably longer than 32(64) bits.

Okay, good to know. The data is typically one or two strings around 16 or 32 bytes each.

> The code tries very hard to not perform any copies. The code you link to is for buffering pieces of data until we have 4x values. If you provide more data than that, we will read directly from the input with minimal copying (beyond that needed for the hash computations itself). The optimal case is if you provide an exact multiple of 4x 32(64) bits.

Okay, I see. Thanks for the clarification.

> Did you compare the end results of the two methods? I would have expected that they produce differing hashes.

I didn't compare them; it only matters to me that it produces a consistent hash relative to themselves.

> It does look like our delta from C has increased a bit, and I might need to look into that:

I think this delta explains the difference I observed between calling into `fasthash`'s C-based XxHash and `twox_hash`.

In my own benchmarking, `twox_hash` is comparable or slower than Rust's `DefaultHasher` presently. (I'm surprised that the rolling seed approach seems to produce a small speedup to bring `twox_hash` closer to `DefaultHasher`, but it could just be noise.)

std::collections::hash_map::DefaultHasher:

```
running 5 tests
test tests::bench_hash1_long  ... bench:          40 ns/iter (+/- 3)
test tests::bench_hash1_short ... bench:          20 ns/iter (+/- 1)
test tests::bench_hash2_long  ... bench:          55 ns/iter (+/- 3)
test tests::bench_hash2_short ... bench:          26 ns/iter (+/- 2)
test tests::bench_variant     ... bench:          89 ns/iter (+/- 10)
```

twox_hash:XxHash32

```
running 5 tests
test tests::bench_hash1_long  ... bench:          52 ns/iter (+/- 4)
test tests::bench_hash1_short ... bench:          30 ns/iter (+/- 2)
test tests::bench_hash2_long  ... bench:          74 ns/iter (+/- 6)
test tests::bench_hash2_short ... bench:          32 ns/iter (+/- 4)
test tests::bench_variant     ... bench:         102 ns/iter (+/- 1)
```

twox_hash:XxHash32 (rolling seed)

```
running 5 tests
test tests::bench_hash1_long  ... bench:          33 ns/iter (+/- 0)
test tests::bench_hash1_short ... bench:          15 ns/iter (+/- 1)
test tests::bench_hash2_long  ... bench:          60 ns/iter (+/- 4)
test tests::bench_hash2_short ... bench:          31 ns/iter (+/- 2)
test tests::bench_variant     ... bench:          92 ns/iter (+/- 12)
```

twox_hash::XxHash64

```
running 5 tests
test tests::bench_hash1_long  ... bench:          49 ns/iter (+/- 1)
test tests::bench_hash1_short ... bench:          29 ns/iter (+/- 2)
test tests::bench_hash2_long  ... bench:          63 ns/iter (+/- 5)
test tests::bench_hash2_short ... bench:          34 ns/iter (+/- 1)
test tests::bench_variant     ... bench:          96 ns/iter (+/- 5)
```

twox_hash:XxHash64 (rolling seed)

```
running 5 tests
test tests::bench_hash1_long  ... bench:          31 ns/iter (+/- 2)
test tests::bench_hash1_short ... bench:          15 ns/iter (+/- 1)
test tests::bench_hash2_long  ... bench:          61 ns/iter (+/- 5)
test tests::bench_hash2_short ... bench:          34 ns/iter (+/- 2)
test tests::bench_variant     ... bench:          98 ns/iter (+/- 7)
```

Closing this since it doesn't seem like non-copying is the problem, but it is unfortunate that `twox_hash` isn't as fast as the C implementation.

**Comment by shepmaster** [comment]
> it only matters to me that it produces a consistent hash relative to themselves.

I'm no hash expert, but having well-distributed hashes is usually a prime concern. That would be my big worry with the rolling seed methodology — that it ends up clustering hashes non-uniformly, ultimately slowing down your end program due to collisions. The fastest hash in a vacuum is `fn hash<T>(_: T) -> u64 { 0 }`, after all 😉 

> one or two strings around 16 or 32 bytes each

You might want to try [ahash](https://crates.io/crates/ahash). I've heard good things, but have no concrete experience myself.

One of the Sip or FNV hashers is also an option.

> it is unfortunate that `twox_hash` isn't as fast as the C implementation.

Agreed! I've opened up #44 for that. You might also want to try PR #39 to see how that performance treats you. I haven't had enough time to sit down and read it thoroughly yet.

**Comment by arxanas** [comment]
> I'm no hash expert, but having well-distributed hashes is usually a prime concern. That would be my big worry with the rolling seed methodology — that it ends up clustering hashes non-uniformly, ultimately slowing down your end program due to collisions

Yes, and good distribution too! I was also worried about the rolling seed system.

> You might want to try ahash. I've heard good things, but have no concrete experience myself.

`ahash` was the fastest hashing solution I tried, but unfortunately, the documentation states it's not for persistent use, and we construct a dependency graph out of these hashes and ship them across machines :(

> One of the Sip or FNV hashers is also an option.

Siphasher and FNV were also comparable in performance to `DefaultHasher` and introduced similar regressions.

---

Here's my internal post comparing the benchmarks, if you're curious (NB: the regression turned out to be closer to 1.5% after making some other fixes to the code):

# Hashing microbenchmarks

I tried implementing our hash function for dependencies in Rust in [redacted], but encountered a performance regression of 4-6% (see [redacted]). I wrote microbenchmarks using Rust's benching framework (10/10 would recommend) and tried out a few hash functions from the `fasthash` package.

The results indicate that we could probably gain that time back by using a faster hash function interface.

The benchmarks are divided up into a few variants:

* `hash1`: hash a single string, like a class name.
* `hash2`: hash two strings, like a class constant (`Foo::BAR` involves hashing `Foo` and `Bar`).
* `long` means use a long string like a class name in www.
* `short` means use a short string like `Foo`.
* The `variant` test constructs an OCaml value and tests traversing it and hashing the components, instead of just the raw hashing performance.

One noteworthy result is that examining the variant at runtime (as OCaml does) increases the cost to hash by 2x-3x, drowning out the raw performance of hashing. If we didn't have to use an OCaml variant, we could significantly improve performance.

There is no streaming implementation for these hashes (they have `std::hash::Hasher` implementations, but that copies byte-strings into a temporary buffer before hashing them all together). I piped the results of `hash32_with_seed` into the next hash in the chain. (I hope that won't cause a lot of collisions 😬).

I also tried some `hash64_with_seed` variants, but I expected those to be slow since the state may be bigger.

# Conclusions

Murmur3 or XxHash could speed us back up by 10%. The numbers are a bit noisy, and the microbenchmarks might not reflect the real world, so I'd have to do some end-to-end performance tests to confirm.

# Results

## `std::collections::hash_map::DefaultHasher` (currently based on SipHasher)

```
running 5 tests
test tests::bench_hash1_long  ... bench:          39 ns/iter (+/- 3)
test tests::bench_hash1_short ... bench:          19 ns/iter (+/- 1)
test tests::bench_hash2_long  ... bench:          55 ns/iter (+/- 4)
test tests::bench_hash2_short ... bench:          25 ns/iter (+/- 1)
test tests::bench_variant     ... bench:         146 ns/iter (+/- 11)
```

## `fasthash::murmur3::hash32_with_seed`

```
running 5 tests
test tests::bench_hash1_long  ... bench:          24 ns/iter (+/- 1)
test tests::bench_hash1_short ... bench:           5 ns/iter (+/- 0)
test tests::bench_hash2_long  ... bench:          36 ns/iter (+/- 3)
test tests::bench_hash2_short ... bench:          10 ns/iter (+/- 0)
test tests::bench_variant     ... bench:         137 ns/iter (+/- 12)
```

## `fasthash::xx::hash32_with_seed`

```
running 5 tests
test tests::bench_hash1_long  ... bench:          15 ns/iter (+/- 2)
test tests::bench_hash1_short ... bench:           5 ns/iter (+/- 0)
test tests::bench_hash2_long  ... bench:          27 ns/iter (+/- 1)
test tests::bench_hash2_short ... bench:          11 ns/iter (+/- 0)
test tests::bench_variant     ... bench:         125 ns/iter (+/- 16)
```

## `fasthash::xx::hash64_with_seed`

```
running 5 tests
test tests::bench_hash1_long  ... bench:          21 ns/iter (+/- 0)
test tests::bench_hash1_short ... bench:           7 ns/iter (+/- 0)
test tests::bench_hash2_long  ... bench:          32 ns/iter (+/- 1)
test tests::bench_hash2_short ... bench:          14 ns/iter (+/- 0)
test tests::bench_variant     ... bench:         135 ns/iter (+/- 15)
```

## `fasthash::city::hash32_with_seed`

```
running 5 tests
test tests::bench_hash1_long  ... bench:          20 ns/iter (+/- 2)
test tests::bench_hash1_short ... bench:           6 ns/iter (+/- 0)
test tests::bench_hash2_long  ... bench:          31 ns/iter (+/- 3)
test tests::bench_hash2_short ... bench:          14 ns/iter (+/- 0)
test tests::bench_variant     ... bench:         153 ns/iter (+/- 12)
```

## `fasthash::spooky::hash32_with_seed`

```
running 5 tests
test tests::bench_hash1_long  ... bench:          26 ns/iter (+/- 2)
test tests::bench_hash1_short ... bench:           9 ns/iter (+/- 0)
test tests::bench_hash2_long  ... bench:          50 ns/iter (+/- 3)
test tests::bench_hash2_short ... bench:          20 ns/iter (+/- 1)
test tests::bench_variant     ... bench:         161 ns/iter (+/- 21)
```

## `fasthash::spooky::hash64_with_seed`

```
running 5 tests
test tests::bench_hash1_long  ... bench:          27 ns/iter (+/- 2)
test tests::bench_hash1_short ... bench:           9 ns/iter (+/- 0)
test tests::bench_hash2_long  ... bench:          47 ns/iter (+/- 3)
test tests::bench_hash2_short ... bench:          19 ns/iter (+/- 1)
test tests::bench_variant     ... bench:         144 ns/iter (+/- 10)
```

## `fasthash::sea::hash64_with_seeds` (1 seed used, remaining 3 set to zero)

```
running 5 tests
test tests::bench_hash1_long  ... bench:          16 ns/iter (+/- 1)
test tests::bench_hash1_short ... bench:           9 ns/iter (+/- 0)
test tests::bench_hash2_long  ... bench:          28 ns/iter (+/- 2)
test tests::bench_hash2_short ... bench:          19 ns/iter (+/- 1)
test tests::bench_variant     ... bench:         124 ns/iter (+/- 9)
```

## `fasthash::mum::hash64_with_seed`

```
running 5 tests
test tests::bench_hash1_long  ... bench:          16 ns/iter (+/- 1)
test tests::bench_hash1_short ... bench:           7 ns/iter (+/- 0)
test tests::bench_hash2_long  ... bench:          24 ns/iter (+/- 3)
test tests::bench_hash2_short ... bench:          14 ns/iter (+/- 1)
test tests::bench_variant     ... bench:         120 ns/iter (+/- 8)
```
