### ISSUE TITLE
How to implement a HashMap with capacity

### ISSUE THREAD

**Issue by hvram1** [shepmaster/twox-hash#61]
I have used the 
<code>
let mut map: HashMap<std::string::String, std::string::String, RandomXxHashBuilder64> =
    Default::default();
</code>
I would like to set the HashMap to a fixed initial capacity . Is there a way to set this up . When I use the with_hasher methods it expects a RandomState

**Comment by SuperFluffy** [comment]
This is strictly speaking not a `twox-hash` question. You are probably looking for `HashMap::with_capacity_and_hasher`, see the API documentation here: https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.with_capacity_and_hasher

**Comment by shepmaster** [comment]
```rust
use std::collections::HashMap;
use twox_hash::RandomXxHashBuilder64;

fn main() {
    let mut map = HashMap::with_capacity_and_hasher(100, RandomXxHashBuilder64::default());
    map.insert(42, "value");

    dbg!(map);
}
```
