### ISSUE TITLE
Resetting the hash

### ISSUE THREAD

**Issue by darleybarreto** [shepmaster/twox-hash#72]
Hi, thanks for porting this to Rust! Is there anything similar to `XXH64_reset` to reset/reuse the hash? Or should I make a new one using `new`? Thanks in advance!

Regards,

**Comment by shepmaster** [comment]
I don't see a particular benefit to having a reset function — I'd just replace the hash value directly and expect the compiler to make up the difference.

**Comment by darleybarreto** [comment]
Hmm, suppose I have the following operations:
```rust
let mut hash = XxHash64::with_seed(0);
hash.write(...);
// reset here
```
How would I replace the internal hash value with a new one based on a seed S?

**Comment by shepmaster** [comment]
I must be missing something. Wouldn't you do

```rust
let mut hash = XxHash64::with_seed(0);
hash.write(...);
// reset here
let mut hash = XxHash64::with_seed(0);
```

**Comment by darleybarreto** [comment]
Oh, I see, basically creating a new one. So if I need to use in a struct, that would be:
```rust
struct MyObject{
    hash: Cell<XxHash64>, // or something else with interior mutability
}
```
Right?

**Comment by shepmaster** [comment]
> if I need to use in a struct

I'd expect that you'd make the methods take `&mut self` so there's no need for interior mutability:

```rust
struct MyObject{
    hash: XxHash64,
}

impl MyObject {
    fn foo(&mut self) {
        self.hash.write(...);
        self.hash = XxHash64::new();
    }
}
```

**Comment by darleybarreto** [comment]
That's one option indeed. Thanks for your quick responses! Stay safe.
