### ISSUE TITLE
Is it possible to update a hash incrementally?

### ISSUE THREAD

**Issue by Crypto-Spartan** [shepmaster/twox-hash#73]
Hi! Thank you for you work to port XXHash to Rust!

I would like to use this crate to hash large files that could be multiple gigabytes in size. Since it isn't practical to read the entire file into memory, my plan was to use a ReadBuf to read the file in chunks. 

The Blake3 hashing algorithm allows for incremental updating of the hash with chunks of data. (See [here](https://github.com/BLAKE3-team/BLAKE3#the-blake3-crate-))

I don't need the cryptographic security that Blake3 provides and I would rather use XXHash since it can process data much faster. Is something like this possible with twox-hash?

**Comment by shepmaster** [comment]
Yes, it implements the [`Hasher`](https://doc.rust-lang.org/nightly/core/hash/trait.Hasher.html) and (optionally) the [`Digest`](https://docs.rs/digest/0.9.0/digest/trait.Digest.html) traits. Both of these allow passing in partial chunks of the whole data. 

See examples in #70 and #42.

**Comment by shepmaster** [comment]
Assuming this answers your question
