### ISSUE TITLE
Usage of hash64

### ISSUE THREAD

**Issue by darleybarreto** [shepmaster/twox-hash#75]
Hi, is `hash64` supposed to be similar to [`XXH64`](https://github.com/Cyan4973/xxHash/blob/0e49217046917180b9118a2d89aceaa76a65cf51/xxhash.h#L2392)? Or did I misunderstand? For what I can tell, calling `XXH64` or using [`XXH64_digest`](https://github.com/Cyan4973/xxHash/blob/0e49217046917180b9118a2d89aceaa76a65cf51/xxhash.h#L2508) with the same seed should give the same hash. The code bellow fails:
```rust
use std::hash::Hasher;
use twox_hash::{xxh3::hash64, XxHash64};

fn main() {
    let mut hasher = XxHash64::with_seed(0);
    let data = b"Hello";
    hasher.write(data);
    let hash1 = hasher.finish();
    let hash2 = hash64(data);
    assert!(hash1==hash2); // 753694413698530628 != 9489064671258106263
}
```

**Comment by shepmaster** [comment]
There are multiple hash implementations in the project. Check the imports you are using:

> ```rust
> use twox_hash::{xxh3::hash64, XxHash64};
> ```

You are using the XXH3 algorithm's `hash64` but the XXH algorithm's `XxHash64`. The two algorithms produce different results.

The accurate comparison would be:

```rust
use std::hash::Hasher;
use twox_hash::xxh3::{hash64, Hash64};

fn main() {
    let mut hasher = Hash64::with_seed(0);
    let data = b"Hello";
    hasher.write(data);
    let hash1 = hasher.finish();
    let hash2 = hash64(data);
    assert_eq!(hash1, hash2);
}
```

**Comment by darleybarreto** [comment]
Oh, I'm stupid... Thanks for clarifying and sorry the inconvenience!
