### ISSUE TITLE
Comparison against `xxhash-rust`?

### ISSUE THREAD

**Issue by firasuke** [shepmaster/twox-hash#84]
How does `twox-hash` compare against [xxhash-rust](https://github.com/DoumanAsh/xxhash-rust) given that they're both unofficial implementations of the `xxhash` algorithms? Are there any benchmarks?

**Comment by SteveLauC** [comment]
[Same question](https://github.com/DoumanAsh/xxhash-rust/issues/10) but in the repo of `xxhash-rust`, and the author of `xxhash-rust` has given [a brief comparison](https://github.com/DoumanAsh/xxhash-rust/issues/10#issuecomment-980488647)
